config/routes.rb
Rails.application.routes.draw do
  resources :violations do
    collection {post :import}
  end

  root to: "violations#index"

end

app/models/violation.rb
class Violation < ActiveRecord::Base
	require 'csv'
	def self.import(file)
    	CSV.foreach(file.path, :headers => true) do |row|
        	Violation.create! row.to_hash
    	end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/violations_controller.rb
class ViolationsController < ApplicationController
  before_action :set_violation, only: [:show, :edit, :update, :destroy]

  # GET /violations
  # GET /violations.json
  def index
    @violations = Violation.all
    @category_list = Violation.all.map{|v| {category: v.violation_category, date: v.violation_date}}
    @category_group = @category_list.group_by{|v| v[:category]}.each{|_, d| d.map!{|v| v[:date]}}
  end

  def import
    Violation.import(params[:file])
    redirect_to root_url, notice: "Violation data successfully imported"
  end

  # GET /violations/1
  # GET /violations/1.json
  def show
  end

  # GET /violations/new
  def new
    @violation = Violation.new
  end

  # GET /violations/1/edit
  def edit
  end

  # POST /violations
  # POST /violations.json
  def create
    @violation = Violation.new(violation_params)

    respond_to do |format|
      if @violation.save
        format.html { redirect_to @violation, notice: 'Violation was successfully created.' }
        format.json { render :show, status: :created, location: @violation }
      else
        format.html { render :new }
        format.json { render json: @violation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /violations/1
  # PATCH/PUT /violations/1.json
  def update
    respond_to do |format|
      if @violation.update(violation_params)
        format.html { redirect_to @violation, notice: 'Violation was successfully updated.' }
        format.json { render :show, status: :ok, location: @violation }
      else
        format.html { render :edit }
        format.json { render json: @violation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /violations/1
  # DELETE /violations/1.json
  def destroy
    @violation.destroy
    respond_to do |format|
      format.html { redirect_to violations_url, notice: 'Violation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_violation
      @violation = Violation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def violation_params
      params.require(:violation).permit(:violation_id, :inspection_id, :violation_category, :violation_date_closed, :violation_type)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/violations_helper.rb
module ViolationsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Violations</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/violations/_form.html.erb
<%= form_for(@violation) do |f| %>
  <% if @violation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@violation.errors.count, "error") %> prohibited this violation from being saved:</h2>

      <ul>
      <% @violation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :violation_id %><br>
    <%= f.number_field :violation_id %>
  </div>
  <div class="field">
    <%= f.label :inspection_id %><br>
    <%= f.number_field :inspection_id %>
  </div>
  <div class="field">
    <%= f.label :violation_category %><br>
    <%= f.text_field :violation_category %>
  </div>
  <div class="field">
    <%= f.label :violation_date %><br>
    <%= f.datetime_select :violation_date %>
  </div>
  <div class="field">
    <%= f.label :violation_date_closed %><br>
    <%= f.datetime_select :violation_date_closed %>
  </div>
  <div class="field">
    <%= f.label :violation_type %><br>
    <%= f.text_field :violation_type %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/violations/edit.html.erb
<h1>Editing Violation</h1>

<%= render 'form' %>

<%= link_to 'Show', @violation %> |
<%= link_to 'Back', violations_path %>

app/views/violations/index.html.erb
<p id="notice"><%= notice %></p>

<h2>Import Violations</h2>
<p>
  Upload the violations file to add the csv to the database.
</p>
<%= form_tag import_violations_path, multipart: true do %>
  <%= file_field_tag :file %>
  <%= submit_tag "Import CSV" %>
<% end %>

<h2>Violation Statistics</h2>
<table class="ui celled table">
  <thead>
    <tr>
      <th>Violation Category</th>
      <th>Category Count</th>
      <th>Earliest Violation</th>
      <th>Latest Violation</th>
    </tr>
  </thead>

  <tbody>
    <% @category_group.each do |category, date| %>
      <tr>
        <td><%= category %></td>
        <td><%= date.length %></td>
        <td><%= date.min %></td>
        <td><%= date.max %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<h2>All Violations</h2>
<table class="ui celled table">
  <thead>
    <tr>
      <th>Violation</th>
      <th>Inspection</th>
      <th>Violation category</th>
      <th>Violation date</th>
      <th>Violation date closed</th>
      <th>Violation type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @violations.each do |violation| %>
      <tr>
        <td><%= violation.violation_id %></td>
        <td><%= violation.inspection_id %></td>
        <td><%= violation.violation_category %></td>
        <td><%= violation.violation_date %></td>
        <td><%= violation.violation_date_closed %></td>
        <td><%= violation.violation_type %></td>
        <td><%= link_to 'Show', violation %></td>
        <td><%= link_to 'Edit', edit_violation_path(violation) %></td>
        <td><%= link_to 'Destroy', violation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/violations/new.html.erb
<h1>New Violation</h1>

<%= render 'form' %>

<%= link_to 'Back', violations_path %>

app/views/violations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Violation:</strong>
  <%= @violation.violation_id %>
</p>

<p>
  <strong>Inspection:</strong>
  <%= @violation.inspection_id %>
</p>

<p>
  <strong>Violation category:</strong>
  <%= @violation.violation_category %>
</p>

<p>
  <strong>Violation date:</strong>
  <%= @violation.violation_date %>
</p>

<p>
  <strong>Violation date closed:</strong>
  <%= @violation.violation_date_closed %>
</p>

<p>
  <strong>Violation type:</strong>
  <%= @violation.violation_type %>
</p>

<%= link_to 'Edit', edit_violation_path(@violation) %> |
<%= link_to 'Back', violations_path %>